# Generated by Django 4.2.11 on 2026-06-09 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsAppEnvio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alerta', models.CharField(db_index=True, max_length=128)),
                ('telefono', models.CharField(max_length=20)),
                ('tipo_alerta', models.CharField(blank=True, default='', max_length=32)),
                ('train_id', models.CharField(blank=True, default='', max_length=64)),
                ('status', models.CharField(choices=[('enviado', 'Enviado'), ('error', 'Error')], default='enviado', max_length=16)),
                ('message_id', models.CharField(blank=True, default='', max_length=128)),
                ('error', models.TextField(blank=True, default='')),
                ('enviado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'indexes': [models.Index(fields=['enviado_en'], name='email_alert_enviado_d2eb4a_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='whatsappenvio',
            constraint=models.UniqueConstraint(fields=('id_alerta', 'telefono'), name='uniq_whatsapp_alerta_telefono'),
        ),
    ]
